GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY3MjQ5OTIsImV4cCI6MTYwNjcyODU5MiwiYXVkIjoiNWZjNGFkODBlYjA1ZmUxYjA4ZDIzOTg2IiwiaXNzIjoiYW5raXRqYWluIn0.z0FO0ubq3XiaNeZPxuF4UKpzEq2GXJuhkOiABehDuqA

###Login Route
POST  http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "vaidehi@gmail.com",
  "password": "123456789"
}
###Register Route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "vishal@gmail.com",
  "password": "123456789",
  "username":"vaidehi",
  "fname": "vaidehi",
  "lname": "mishra",
  "phone": "9856234526",
  "insta":" ",
  "facebook": " ",
  "linkedin": " ",
  "city": "Delhi",
  "address": "Hari Nagar",
  "bio": "create you own sunshine dddddd ffffff ggggggg hhhhh",
  "dateOfBirth": "1994-03-26",
  "gender": "female",
  "designation":"backend deeveloper",
  "image": " "
}

### Refresh token Route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDY3MTA3NDIsImV4cCI6MTYzODI2ODM0MiwiYXVkIjoiNWZjNDc1ZDY2NWNjYjExN2ZjYzVlZGU1IiwiaXNzIjoiYW5raXRqYWluIn0.1NXudiNO79GCoNukIR22z9bOGisSE2LGPIMC3--EUNc"
}

### Logout Route
DELETE  http://localhost:3000/auth/logout

GET http://localhost:3000
 "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDk4NTc4MTgsImV4cCI6MTYwOTg2MTQxOCwiYXVkIjoiNWZmNDdiMWEyODA5NjE1MjI0NzZjYTgyIiwiaXNzIjoiYW5raXRqYWluIn0.j9q5CgloLk0PHrJ8KxQAjcjklylOv1Bp_e_U1QmUu50",

### get profile Route
GET http://localhost:3000/getProfile

### update profile Route
PUT http://localhost:3000/updateProfile
Content-Type: application/json

{
  "username":"mahi",
  "email": "sujat@gmail.com",
  "fname": "sonlm",
  "lname": "garlg",
  "phone": "9856231476",
  "insta": " ",
  "facebook": " ",
  "linkedin": " ",
  "city": "Gurgaon",
  "address": "Hanuman Nagar",
  "bio": "create you own sunshine dddddd ffffff ggggggg hhhhh",
  "dateOfBirth": "1994-03-26",
  "gender": "female",
  "designation":"backend deeveloper",
  "image": " ",
  "password": "123456789"
}
### Contact Route
POST http://localhost:3000/con/createContact
Content-Type: application/json

{
  "username":"arshita",
  "email":"ashi@gmail.com",
  "category":"enquiry",
  "associty":"lucknow",
  "message":"i am an employee of desreach .",
  "verifycode":"2234"
}


### Mailer Route
POST http://localhost:3000/mailer
Content-Type: application/json

{
  "from" : "shraddha@desreach.com",
   "to" : "rhtg12@gmail.com",
   "subject" : "welcome to desreach ",
    "text" : "hello "
}
